# Generated by Django 4.0.4 on 2022-05-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='liked_warbler',
            new_name='liked_messages',
        ),
    ]
