# Generated by Django 4.0.4 on 2022-05-23 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbles', '0001_initial'),
        ('users', '0003_rename_liked_warbler_user_liked_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_messages',
            field=models.ManyToManyField(related_name='likers', to='warbles.message'),
        ),
    ]
